// swift-tools-version: 6.0
import PackageDescription

// MatrixNet core libraries.
//
// The pure-logic, fully testable core of MatrixNet lives here as a local Swift
// package so that `swift test` (and CI) can exercise it without Xcode. The macOS
// app and the privileged capture helper are Xcode targets (generated by XcodeGen
// from `project.yml`) that depend on these products.
//
// All targets build in Swift 6 language mode (strict concurrency). Modules are
// added to this manifest as each is implemented test-first.

let package = Package(
    name: "MatrixNetCore",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        .library(name: "MatrixNetModel", targets: ["MatrixNetModel"]),
        .library(name: "MatrixNetDissection", targets: ["MatrixNetDissection"]),
        .library(name: "MatrixNetCapture", targets: ["MatrixNetCapture"]),
    ],
    targets: [
        .target(
            name: "MatrixNetModel",
            path: "Sources/MatrixNetModel"
        ),
        .target(
            name: "MatrixNetDissection",
            dependencies: ["MatrixNetModel"],
            path: "Sources/MatrixNetDissection"
        ),
        .target(
            name: "MatrixNetCapture",
            dependencies: ["MatrixNetModel"],
            path: "Sources/MatrixNetCapture"
        ),
        .testTarget(
            name: "MatrixNetModelTests",
            dependencies: ["MatrixNetModel"],
            path: "Tests/MatrixNetModelTests"
        ),
        .testTarget(
            name: "MatrixNetDissectionTests",
            dependencies: ["MatrixNetDissection", "MatrixNetModel"],
            path: "Tests/MatrixNetDissectionTests"
        ),
        .testTarget(
            name: "MatrixNetCaptureTests",
            dependencies: ["MatrixNetCapture", "MatrixNetModel"],
            path: "Tests/MatrixNetCaptureTests"
        ),
        .executableTarget(
            name: "matrixnet-smoke",
            dependencies: ["MatrixNetCapture", "MatrixNetModel"],
            path: "Tools/SmokeNStat"
        ),
    ]
)
